### ISSUE TITLE
AGPL is missing

### ISSUE THREAD

**Issue by mmoya** [bevry/staticsitegenerators-list#206]
The Affero GPL is missing as valid license. There are some SSG published under this license, for example Pelican.

**Comment by jaspervdj** [comment]
If I understand the AGPL correctly, it seems that it could be considered a "variation of the GPL", no? Apparently it is designed to close a technical loophole in the GPL.

**Comment by mmoya** [comment]
In my opinion, they are seen more as _different licenses_ (they even have different wikipedia pages) than _one being the other plus a paragraph_.

If you focus on content, BSD-2 clause and MIT are less different than GPL and AGPL are.

**Comment by balupton** [comment]
Superseded by https://github.com/bevry/staticsitegenerators-list/issues/221
