### ISSUE TITLE
Move to SPDX codes for our licenses

### ISSUE THREAD

**Issue by balupton** [bevry/staticsitegenerators-list#221]
So SPDX has emerged as the standard for license codes and formats — http://spdx.org/licenses/ — perhaps it would make sense for us to move to it over our current ad-hoc methodology now.

This would eliminate our current categorisation of the licenses (e.g. all GPL licenses together), but that may not actually be that useful in practicality over having the specific licenses actually listed.

Dual licenses could still be listed as the SPDX format supports that: https://github.com/kemitchell/spdx.js#composite-license-expressions

What's everyone's thoughts? /cc @bevry/ssg-listing-team

**Comment by davisonio** [comment]
I think this is a good idea, it's a bit of a drawback having to add a license to our known licenses list and dual licensing is needed by some projects.

We should check out the [new API for licenses](https://developer.github.com/v3/licenses/) we could use this to automatically add license info to the list based on the license file within the GitHub repo.

**Comment by jaspervdj** [comment]
Sounds good to me.

**Comment by balupton** [comment]
Great, let's proceed with this.

> We should check out the new API for licenses we could use this to automatically add license info to the list based on the license file within the GitHub repo.

This sound like a great first step, as it could save us a lot of trouble in determining exact licenses.

**Comment by balupton** [comment]
Perhaps we can setup a hack day for this over the holidays? Do a Google+ Hangout on Air or something.

Things to be tackled:

- Updating the verify script
- Update the enhancement script (I'll dib this)
- Update the license fields for the listings

Questions remaining:

- For the sake of compatibility in case anything is using the file and depending on the "license" field, perhaps we should keep the "license" field as is, but introduce a new "spdx" field for the updated format, and leave a deprecated notice for the "license" field, and completely remove it in February or something.

**Comment by balupton** [comment]
This can essentially go two ways:

1. Thorough: We go through each item and check for dual licenses, and other license combinations, and what specific subset of the current value we have is being used, and update accordingly (e.g. GPL would be changed to LGPL if that was the actual case)
2. Simple: We update our current values to the SPDX equivalents, not caring about correctness (e.g. LGPL values would be ignored)

**Comment by balupton** [comment]
Let's do the second and leave the onus on the SSG authors and community to keep them updated.

I'll update the script to be node.js based and use https://www.npmjs.com/package/spdx for verification

**Comment by balupton** [comment]
Doing this now.

**Comment by balupton** [comment]
All done.
