### ISSUE TITLE
Motivation to create another list ?

### ISSUE THREAD

**Issue by ainthek** [bevry/staticsitegenerators-list#226]
are you aware of this project ?

https://github.com/netlify/staticgen
http://www.staticgen.com

why not sharing knowledge in one place ?

**Comment by davisonio** [comment]
StaticGen was started after this project was started so perhaps you should be asking them why they decided to create another list when this one was already in existence?

This project is intended to be a complete list of static site generators and soon to be a place to also find other resources related to static site generators.

StaticGen only strictly allows static site generators and they don't allow flat-file CMSs. They also don't seem to list any closed-source options or off-github projects.

**Comment by ainthek** [comment]
You are right, I have counted both list and yours is much longer and complete
Maybe if the teams join forces it would be faster to create something more comprehensive.

However their web site si much nicer ;-)
close

**Comment by balupton** [comment]
We're open to collaborating with as many people as possible. Collaboration is a large part of this project, as seen by the >150 contributors :+1:
