### ISSUE TITLE
Suggestion: Add an "abandoned" field

### ISSUE THREAD

**Issue by dertuxmalwieder** [bevry/staticsitegenerators-list#283]
Some SSGs like Acrylamid have "abandoned" in their description (or repository). Maybe this should be unified for filtering?

**Comment by balupton** [comment]
Sure. For now this is kind of being accomplished via the last update time. I also plan on adding health information #271 to the repo, that could probably accomplish this automatically. I plan on doing #271 soonish, so maybe we can see if that accomplishes this without having need to do it manually.

**Comment by dertuxmalwieder** [comment]
Slow development does not necessarily mean a halted development. Some of my projects haven't seen a public update for years but I wouldn't call them "abandoned".

**Comment by balupton** [comment]
@dertuxmalwieder good point, let's introduce the field - I can give you commit rights, you seem to know what you are doing!

**Comment by dertuxmalwieder** [comment]
Famous last words...

**Comment by balupton** [comment]
@dertuxmalwieder invite sent

**Comment by balupton** [comment]
@dertuxmalwieder joining slack.bevry.me would probably be useful

**Comment by dertuxmalwieder** [comment]
I don't really like Slack. Don't you have IRC?  :-/

**Comment by dertuxmalwieder** [comment]
Fixed btw.

**Comment by balupton** [comment]
@dertuxmalwieder maybe we can setup a slack IRC adapter, I hear that is a thing

**Comment by dertuxmalwieder** [comment]
Hooray.

**Comment by balupton** [comment]
@dertuxmalwieder IRC bots now setup, https://discuss.bevry.me/t/official-irc-chat-rooms/54?u=balupton
