### ISSUE TITLE
Should there be a flag to explicitly disable getting the website from Github?

### ISSUE THREAD

**Issue by dertuxmalwieder** [bevry/staticsitegenerators-list#285]
While maintaining the SSG list, I noticed that some (abandoned) projects still have a website entry which is now pointing to something entirely different, e.g. [Bolt](https://github.com/benmcredmond/Bolt). Probably this should be respected.

**Comment by dertuxmalwieder** [comment]
Random idea:

    <% if project.abandoned: %>
        <abbr title="<%= project.name %> (abandoned)"><%= project.name %></abbr>
    <% else: %>
        <% if project.website: %>
            <a href="<%=project.website%>" title="Visit <%= project.name %>&rsquo;s website">
                <%= project.name %>
            </a>
        <% else: %>
            <%= project.name %>
        <% end %>
    <% end %>

**Comment by balupton** [comment]
I think we should do as we do with licenses and do community outreach by posting issues on their associated repos to get their data updated. It has worked very well for licensing thus far. People are pretty receptive to fixing things.

**Comment by dertuxmalwieder** [comment]
Unless they haven't even logged in for years.

**Comment by balupton** [comment]
Does `website: false` work?

**Comment by dertuxmalwieder** [comment]
It should. (The website still has caching issues, right?)

**Comment by balupton** [comment]
@dertuxmalwieder okay, caching issues fixed
