### ISSUE TITLE
Website not reflecting list

### ISSUE THREAD

**Issue by staticcharge** [bevry/staticsitegenerators-list#321]
There are at least 463 entries in https://github.com/bevry/staticsitegenerators-list/blob/master/list.json but there are only 458 entries on https://staticsitegenerators.net/.

As an example, I see the project named 'sitio' in the source code but not in the website. Why is it so?

**Comment by balupton** [comment]
this issue is now resolved — the list is now published to a new package version on every passing commit — the website will switch to a dynamic runtime
