### ISSUE TITLE
Publii

### ISSUE THREAD

**Issue by Verhoeckx** [bevry/staticsitegenerators-list#424]
You miss the greatest Static Site Generator: Publii  :-)!

The great thing about Publii is that, it isn't just a Static Site Generator, it's also a full-fledged Content Management System!

You can find more about Publii here:
https://getpublii.com/

License: GPL-3.
Language: JavaScript
Created: here you can find the first blog post: https://getpublii.com/blog/publii-static-website-cms.html
Updated: 9 november 2020, +/- 3 months ago

**Comment by dertuxmalwieder** [comment]
Awesome. Looking forward to your Pull Request! :-)

**Comment by Verhoeckx** [comment]
No problem! I will send you pull request!

**Comment by dertuxmalwieder** [comment]
Ah, I love automatic GitHub actions. Thank you for your PR!

**Comment by Verhoeckx** [comment]
When will the website be updated? This is still something you have to do manually, I think?

**Comment by Verhoeckx** [comment]
@dertuxmalwieder : I think you still have to update the website?

**Comment by dertuxmalwieder** [comment]
This is something that should be done by the project leaders.

**Comment by Verhoeckx** [comment]
And who are the project leaders? How can I notify them?

**Comment by dertuxmalwieder** [comment]
Ping! @balupton :-)

**Comment by Verhoeckx** [comment]
Okay, super, thanks!

**Comment by balupton** [comment]
The website should auto update but there is an issue with it. I will redo it all in the coming weeks.
