### ISSUE TITLE
add more fields to the description

### ISSUE THREAD

**Issue by anarcat** [bevry/staticsitegenerators-list#7]
It would be nice to add more fields to the description here. For example, we could have:
- maturity (alpha/beta/etc)
- last release (number and date)
- programming language and LOC
- syntax (e.g. mdwn, pandoc, etc)
- templating system
- other features (cgi editing support, rsync deployment and what not)

I would even dare saying that the link to the github project isn't that important and could be replaced by just a link to the homepage... if we want to save space, that is.

**Comment by jonschlinkert** [comment]
Also would be nice to add `free` versus `paid`
